### ISSUE TITLE
Could not load library libcudnn_ops_infer.so.8

### ISSUE THREAD

**Issue by Benny739** [guillaumekln/faster-whisper#516]
`
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
`

I'm using "nvidia/cuda:12.2.0-base-ubuntu20.04" image on google cloud with nvidia t4 gpus.

The normal whisper package model works fine on cuda.

**Comment by phineas-pta** [comment]
need cuda 11.8

**Comment by Purfview** [comment]
> Could not load library libcudnn_ops_infer.so.8

You can find cuBLAS and cuDNN libs for Linux there at releases -> https://github.com/Purfview/whisper-standalone-win

Not tested, report if they work.

**Comment by bestasoff** [comment]
Check if your `LD_LIBRARY_PATH` is specified and points to your cuda location.

**Comment by justinthelaw** [comment]
I am also having a similar problem. I tried uninstalling cuda-12.2 and cudaNN-9.x, and installing and pointing at cuda-11.8.0. I also used the pip-based command in the instructions and set my $LD_LIBRARY_PATH in the terminal prior to running the script.

Is it possible there are disconnects either between Jupyter Notebook and the actual virtual environment, or maybe the virtual environment and the base OS?

**Comment by justinthelaw** [comment]
@bestasoff @Benny739 I was able to fix this particular issue by uninstalling all of the NVIDIA dependencies for cuda12.x, and just reinstalling cuda11.8. Now, I am running into a different problem that I'll discuss in a different issue..

**Comment by bakermanbrian** [comment]
Having a similar issue. I'm trying to get Faster Whisper to run off a docker build. 

I'm trying to use the docker image:
pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime

Unfortunately, getting this libcudnn_ops_infer.so.8 issue as well. Anyone know how I might add the necessary additional libraries? I can't use the official Nvidia one it seems (was too large for my smaller system to handle).

**Comment by einarpersson** [comment]
> need cuda 11.8

As in "at least 11.8" or "exactly 11.8"? I have CUDA Version: 12.0 installed (in WSL2/Ubuntu) but get this error.

**Comment by justinthelaw** [comment]
If you are installing CUDA via pip in a virtual environment (and the same goes for on host, VM, or in a container):

```bash
# point to VENV's local CUDA 11.8 python lib
export LD_LIBRARY_PATH=${PWD}/.venv/lib64/python3.11/site-packages/nvidia/cublas/lib:${PWD}/.venv/lib64/python3.11/site-packages/nvidia/cudnn/lib
```

**Comment by Luca-Pozzi** [comment]
Hi everybody, and thank you for helping me in solving this issue!

Expanding on @justinthelaw [comment](https://github.com/SYSTRAN/faster-whisper/issues/516#issuecomment-1902687567) I have used the following command instead:

```
path LD_LIBRARY=$LD_LIBRARY_PATH:$HOME/path/to/venv/lib64/python3.x/site-packages/nvidia/cublas/lib:$HOME/path/to/venv/lib64/python3.x/site-packages/nvidia/cudnn/lib
```

With this you append the paths to the `$LD_LIBRARY_PATH` rather than overwriting it. In the path, `/path/to/venv` must be substituted with the actual location (and name) of your virtual environment. The same applies to `python3.x`, where the `x` must be substituted with the Python version in use.

As a final comment, `export` applies only to the terminal in which it is issued. One may consider to append it to the `$HOME/.bashrc` script to make it persistent.

**Comment by fusesid** [comment]
@justinthelaw I am facing same issue. Here are the answers to the question you asked to answer.

**NVIDIA-SMI**
![Screenshot from 2024-02-27 10-54-30](https://github.com/SYSTRAN/faster-whisper/assets/138424720/b1071598-bf8b-4a5e-b271-b4da0cfb45d9)

**NVCC --VERSION**
![Screenshot from 2024-02-27 10-54-43](https://github.com/SYSTRAN/faster-whisper/assets/138424720/709f57b5-46ed-45c9-9546-27bb9e305362)

**PIP DEPENDENCIES INSTALLED**
`
```
absl-py==2.0.0
accelerate==0.22.0
aiofiles==23.2.1
aiohttp==3.8.5
aiosignal==1.3.1
altair==5.1.1
anyio==3.7.1
appdirs==1.4.4
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1698341106958/work
async-timeout==4.0.3
attrs==23.1.0
av==11.0.0
awscli==1.29.40
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
beautifulsoup4==4.12.2
blis==0.7.10
boto3==1.28.1
botocore==1.31.40
bpemb==0.3.4
catalogue==2.0.9
certifi==2023.7.22
charset-normalizer==3.2.0
click==8.1.7
cloudpickle==2.2.1
cmake==3.27.2
colorama==0.4.4
coloredlogs==15.0.1
comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1704278392174/work
confection==0.1.1
conllu==4.5.3
contourpy==1.1.0
ctranslate2==4.0.0
cycler==0.11.0
cymem==2.0.7
dataclasses-json==0.5.14
datasets==2.16.1
debugpy @ file:///croot/debugpy_1690905042057/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
deepeval==0.20.43
Deprecated==1.2.14
dill==0.3.7
distro==1.9.0
docker-pycreds==0.4.0
docutils==0.16
en-core-web-lg @ https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.6.0/en_core_web_lg-3.6.0-py3-none-any.whl#sha256=9012584a8fcf5bc61bedb13a4b511fb81ffff9f770958ee06366671be10632e9
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1643888246732/work
exceptiongroup==1.1.3
execnet==2.0.2
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1698579936712/work
fastapi==0.103.1
faster-whisper==1.0.0
ffmpy==0.3.1
filelock==3.12.3
flair==0.12.2
flatbuffers==23.5.26
fonttools==4.42.1
frozenlist==1.4.0
fsspec==2023.9.0
ftfy==6.1.1
future==0.18.3
gdown==4.4.0
gensim==4.3.2
gitdb==4.0.11
GitPython==3.1.41
gradio==3.35.0
gradio_client==0.5.0
greenlet==2.0.2
h11==0.14.0
httpcore==0.17.3
httptools==0.6.1
httpx==0.24.1
huggingface-hub==0.20.2
humanfriendly==10.0
hyperopt==0.2.7
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1703631723894/work
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1680185408135/work
Janome==0.5.0
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1696326070614/work
Jinja2==3.1.2
jmespath==1.0.1
joblib==1.3.2
jsonpatch==1.33
jsonpointer==2.4
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1654730843242/work
jupyter_core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1704727023078/work
kiwisolver==1.4.5
langchain==0.0.229
langchain-core==0.1.10
langchain-openai==0.0.2.post1
langchainplus-sdk==0.0.20
langcodes==3.3.0
langdetect==1.0.9
langsmith==0.0.80
linkify-it-py==2.0.2
lit==16.0.6
lxml==4.9.3
markdown-it-py==2.2.0
MarkupSafe==2.1.3
marshmallow==3.20.1
matplotlib==3.7.2
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1660814786464/work
mdit-py-plugins==0.3.3
mdurl==0.1.2
more-itertools==10.1.0
mpld3==0.3
mpmath==1.3.0
multidict==6.0.4
multiprocess==0.70.15
murmurhash==1.0.9
mypy-extensions==1.0.0
nest_asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1705352640985/work
networkx==3.1
nltk==3.8.1
numexpr==2.8.5
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu11==8.5.0.96
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu11==10.9.0.58
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu11==10.2.10.91
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu11==11.7.4.91
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu11==2.14.3
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.101
nvidia-nvtx-cu11==11.7.91
nvidia-nvtx-cu12==12.1.105
onnxruntime==1.17.1
openai==0.27.8
openapi-schema-pydantic==1.2.4
orjson==3.9.5
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1696202382185/work
pandas==2.1.0
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
pathy==0.10.2
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1667297516076/work
phonenumbers==8.13.19
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow==10.0.0
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1701708255999/work
pluggy==1.3.0
portalocker==2.8.2
pptree==3.1
preshed==3.0.8
presidio-analyzer==2.2.33
presidio-anonymizer==2.2.33
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1702399386289/work
protobuf==3.20.3
psutil @ file:///opt/conda/conda-bld/psutil_1656431268089/work
psycopg2==2.9.9
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
py4j==0.10.9.7
pyarrow==14.0.2
pyarrow-hotfix==0.6
pyasn1==0.5.0
pycryptodome==3.18.0
pydantic==1.10.12
pydub==0.25.1
Pygments==2.16.1
pyparsing==3.0.9
pysbd==0.3.4
PySocks==1.7.1
pytest==7.4.4
pytest-xdist==3.5.0
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
python-dotenv==1.0.0
python-multipart==0.0.6
pytorch_revgrad==0.2.0
pytz==2023.3.post1
PyYAML==6.0.1
pyzmq @ file:///croot/pyzmq_1686601365461/work
ragas==0.0.22
referencing==0.30.2
regex==2023.8.8
requests==2.31.0
requests-file==1.5.1
rich==13.7.0
rouge-score==0.1.2
rpds-py==0.10.2
rsa==4.7.2
s3transfer==0.6.2
safetensors==0.3.3
scikit-learn==1.3.0
scipy==1.11.2
segtok==1.5.11
semantic-version==2.10.0
sentence-transformers==2.2.2
sentencepiece==0.1.99
sentry-sdk==1.39.2
setproctitle==1.3.3
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
smart-open==6.3.0
smmap==5.0.1
sniffio==1.3.0
soupsieve==2.5
spacy==3.6.1
spacy-legacy==3.0.12
spacy-loggers==1.0.4
SQLAlchemy==2.0.20
sqlitedict==2.1.0
srsly==2.4.7
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
starlette==0.27.0
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
thinc==8.1.12
threadpoolctl==3.2.0
tiktoken==0.5.2
tldextract==3.4.4
tokenizers==0.13.3
tomli==2.0.1
toolz==0.12.0
torch==2.1.2
torchvision==0.16.2
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1648827245914/work
tqdm==4.66.1
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1704212992681/work
transformer-smaller-training-vocab==0.3.1
transformers==4.30.2
triton==2.1.0
typer==0.9.0
typing-inspect==0.9.0
typing_extensions==4.7.1
tzdata==2023.3
uc-micro-py==1.0.2
urllib3==1.26.16
uvicorn==0.23.2
uvloop==0.19.0
wandb==0.16.2
wasabi==1.1.2
watchfiles==0.21.0
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1704731205417/work
websockets==11.0.3
Wikipedia-API==0.6.0
wrapt==1.15.0
xxhash==3.4.1
yarl==1.9.2
zipp==3.16.2
```
`

LOCATION:
`/home/anaconda3/envs/my_env/bin`

**Comment by SeaDude** [comment]
> If you are installing CUDA via pip in a virtual environment (and the same goes for on host, VM, or in a container):
> 
> ```shell
> # point to VENV's local CUDA 11.8 python lib
> export LD_LIBRARY_PATH=${PWD}/.venv/lib64/python3.11/site-packages/nvidia/cublas/lib:${PWD}/.venv/lib64/python3.11/site-packages/nvidia/cudnn/lib
> ```
> 
> My previous comment about needing to downgrade my host CUDA toolkit and drivers was wrong. You just need to have a host system with drivers that supports up to or past the CUDA version required by the library.
> 
> If you continue to have trouble, please provide the pip dependencies installed in your dev/prod environment, where those deps are located in the environment, and also post the outputs of the following:
> 
> ```shell
> nvidia-smi
> nvcc --version
> ```

---

Hm...installing the NVIDIA pre-reqs listed in the README borked my GPU. Had to `sudo apt-get purge nvidia-*` then `sudo apt autoremove` then `sudo apt install system76-driver-nvidia` to get the factory drivers back. 

Could you suggest an install method that works with these GPU specs?

![image](https://github.com/SYSTRAN/faster-whisper/assets/8636973/8f636c88-72ef-4085-84cf-8beb9036e8df)

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
```

**Comment by uumami** [comment]
It happened in the `docker-compose` / `docker`. To solve it I had to execute the next command inside the docker:
```
 export LD_LIBRARY_PATH=/usr/local/lib/python3.9/site-packages/torch/lib:$LD_LIBRARY_PATH

```

**Comment by HsinChiaChen** [comment]
Use python to check the path of the lib
```
import os
import nvidia.cublas.lib
import nvidia.cudnn.lib

print(os.path.dirname(nvidia.cublas.lib.__file__) + ":" + os.path.dirname(nvidia.cudnn.lib.__file__))
```

Add the LD_LIBRARY_PATH variable in bashrc, the content is the data printed by python.
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/usr/.local/lib/python3.10/site-packages/nvidia/cublas/lib:/home/usr/.local/lib/python3.10/site-packages/nvidia/ cudnn/lib
```
After modification, remember to close the current terminal and reopen a new terminal so that the above configuration will take effect.

**Comment by CrazyBunQnQ** [comment]
it work for me:
```shell
pip install torch --index-url https://download.pytorch.org/whl/cu121
```

**Comment by disbullief** [comment]
For everyone that has this issue, what fixed it for me was to include in the the path to torch too in  `LD_LIBRARY_PATH`.
The docker image I run is `pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime`

`export LD_LIBRARY_PATH=`python3 -c 'import os; import nvidia.cublas.lib; import nvidia.cudnn.lib; import torch; print(os.path.dirname(nvidia.cublas.lib.__file__) + ":" + os.path.dirname(nvidia.cudnn.lib.__file__) + ":" + os.path.dirname(torch.__file__) +"/lib")'``

**Comment by otonoton** [comment]
I do not have an NVIDIA GPU, do not want to use CUDA and cannot install CUDA.

How can I use this program without installing any cuda packages?

**Comment by disbullief** [comment]
@otonoton I think that your best bet would be to use [Whisper C++](https://github.com/ggerganov/whisper.cpp)

**Comment by otonoton** [comment]
I have been using it but I was hoping to use faster-whisper for obvious reasons...

**Comment by Prashant446** [comment]
> For everyone that has this issue, what fixed it for me was to include the path to torch too in `LD_LIBRARY_PATH`.

For posterity: if you need to add torch library path, you don't need to add other libraries as a set of cuda libraries are also bundled with it:
 ```
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`python3 -c 'import os; import torch; print(os.path.dirname(torch.__file__) +"/lib")'`
 ```

**Comment by fedirz** [comment]
I've had this issue when using `12.4.1-cudnn-devel-ubuntu22.04` in my `Dockerfile`, switching to `nvidia/cuda:12.2.2-cudnn8-runtime-ubuntu22.04` has resolved the issue for me without resorting to the `LD_LIBRARY_PATH` hackery and pip installing the drivers. 

I think the issue with using the latest cuda image is because it ships with `cuDNN 9` which according to the README.md isn't supported.

I hope this helps!

Full `Dockerfile` for context:
```
FROM nvidia/cuda:12.2.2-cudnn8-runtime-ubuntu22.04
RUN apt-get update && \
    apt-get install -y curl software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install python3.11 python3.11-distutils && \
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11
RUN pip install --no-cache-dir poetry==1.8.2
WORKDIR /root/speaches
COPY pyproject.toml poetry.lock ./
RUN poetry install
COPY ./speaches ./speaches
ENTRYPOINT ["poetry", "run"]
CMD ["uvicorn", "speaches.main:app"]
```

**Comment by storytracer** [comment]
For me installing the cuDNN 8  libraries using `sudo apt install libcudnn8` on Ubuntu 22.04 fixed the issue!

**Comment by wolfassi123** [comment]
> Having a similar issue. I'm trying to get Faster Whisper to run off a docker build.
> 
> I'm trying to use the docker image: pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime
> 
> Unfortunately, getting this libcudnn_ops_infer.so.8 issue as well. Anyone know how I might add the necessary additional libraries? I can't use the official Nvidia one it seems (was too large for my smaller system to handle).

Did you manage to fix this on the docker container?

**Comment by msj121** [comment]
> For me installing the cuDNN 8 libraries using `sudo apt install libcudnn8` on Ubuntu 22.04 fixed the issue!

Just for others - I had used sudp apt install libcudnn9 - that did not work - but 8 does work.

**Comment by dantanqikun** [comment]
> For me installing the cuDNN 8 libraries using `sudo apt install libcudnn8` on Ubuntu 22.04 fixed the issue!

it works for me as well, after you install libcudnn8,  you will get  libcudnn_ops_infer.so installed as well as other lib,
just wonder why libcudnn9 installation are missing those lib

**Comment by Maxime479** [comment]
> For me installing the cuDNN 8 libraries using `sudo apt install libcudnn8` on Ubuntu 22.04 fixed the issue!

OMG you saved me ! Thank you so much.

**Comment by miaohf** [comment]
I used in Ubuntu 24.04
`sudo apt install nvidia-cudnn`

**Comment by Nik-Kras** [comment]
Just a note: vast.ai machine was Ubuntu 22.04 x84_64 machine. And I tested it for this machine only.

Here is what helped me:

1. Install NVCC driver
```bash
sudo apt install nvidia-cuda-toolkit
```

2. Install cuDNN (Version 8!)

It is not trivial to install version 8!
If you go to the official website to install cuDNN and enter your machine's details, you will only get the latest version — version 9. I tried it, but it doesn't work (even when you link from calls of version 8 to version 9).

Official [Website](https://developer.nvidia.com/cudnn)

So, you would need to go to [archive](https://developer.nvidia.com/rdp/cudnn-archive) and submit your request for version 8.

After that, you will get a file called `.deb`. In my case, I got `cudnn-local-repo-ubuntu2204-8.9.7.29_1.0-1_amd64.deb`

Here is how you install it:

```bash
sudo dpkg -i cudnn-local-repo-ubuntu2204-8.9.7.29_1.0-1_amd64.deb
sudo cp /var/cudnn-local-repo-ubuntu2204-8.9.7/cudnn-local-*.gpg /usr/share/keyrings/
```

Maybe you would also need to do that:

```bash
sudo apt-get update
sudo apt-get install --reinstall libcudnn8 libcudnn8-dev libcudnn8-samples
```

3. Verify installation

```bash
ls /usr/lib/x86_64-linux-gnu/libcudnn* | grep libcudnn_ops_infer.so.8
ls /usr/lib/x86_64-linux-gnu/libcudnn* | grep libcudnn_cnn_infer.so.8
```

**Comment by koen-dejonghe** [comment]
I installed whisperX.
It uses faster-whisper, and it works oob.

https://github.com/m-bain/whisperX

**Comment by saiakarsh-augnito** [comment]
> For me installing the cuDNN 8 libraries using `sudo apt install libcudnn8` on Ubuntu 22.04 fixed the issue!

Just doing this command fixed the issue for me. No need for `export LD_LIBRARY_PATH=...` in my case.

**Comment by JuanPZuluaga** [comment]
Another solution is to install `nvidia-cudnn` in your venv. You could simply run: 

```
pip install nvidia-pyindex
pip install nvidia-cudnn
```

link: https://pypi.org/project/nvidia-cudnn/

That really worked for me!

**Comment by seaBFH** [comment]
cudnn 8.x.x.x is very important. 
https://docs.nvidia.com/deeplearning/cudnn/latest/installation/linux.html
```bash
python3 -m pip install nvidia-cudnn-cu11==8.9.6.50
```

**Comment by freesiafreesia** [comment]
> cudnn 8.x.x.x is very important. https://docs.nvidia.com/deeplearning/cudnn/latest/installation/linux.html
> 
> ```shell
> python3 -m pip install nvidia-cudnn-cu11==8.9.6.50
> ```

Thanks @seaBFH !
After that, find where they are.

```shell
find . -name 'libcublas.so*' -o -name 'libcudnn_ops*'
```

If you see like this,
    ./.venv/lib/python3.10/site-packages/nvidia/cudnn/lib/libcudnn_ops_train.so.8
    ./.venv/lib/python3.10/site-packages/nvidia/cudnn/lib/libcudnn_ops_infer.so.8

Then, do like this. It worked for me.

```shell
export LD_LIBRARY_PATH=${PWD}/.venv/lib/python3.10/site-packages/nvidia/cudnn/lib
```

**Comment by squizzster** [comment]
> it work for me:
> 
> ```shell
> pip install torch --index-url https://download.pytorch.org/whl/cu121
> ```

I tried, re-installing, adding paths and all sorts... 
THIS WORKED FOR ME!

```
python run.py
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
```

```
pip install torch --index-url https://download.pytorch.org/whl/cu1212-8.9.2.26
(sts) [mark@localhost faster_whisper]$ python run.py
Detected language 'en' with probability 0.649414
[0.00s -> 1.40s]  Yeah, hello, yea
```h,

**Comment by fedexman** [comment]
To add to [freesiafreesia](https://github.com/freesiafreesia) Solution, if you get after his solution this error
`RuntimeError: Library libcublas.so.12 is not found or cannot be loaded`. I solved it by adding the two path to the env variable:
```
$pip install nvidia-cudnn-cu12==9.1.1.17
.....
$ find . -name 'libcublas.so*' -o -name 'libcudnn_ops*'
./.venv/lib/python3.12/site-packages/nvidia/cublas/lib/libcublas.so.12
./.venv/lib/python3.12/site-packages/nvidia/cudnn/lib/libcudnn_ops.so.9
```
`export LD_LIBRARY_PATH=./.venv/lib/python3.12/site-packages/nvidia/cudnn/lib/:./.venv/lib/python3.12/site-packages/nvidia/cublas/lib/`

**Comment by Petruc-Rares** [comment]
I tried all solutions above + gone through Requirements section of the documentation, and for me it didn't work.

What I did was to **downgrade** my **ctranslate2** (prev version 4.4.0) by running:
```
pip install --force-reinstall ctranslate2==3.24.
```
followed by:
```
pip install torch==2.1.0
pip install nvidia-cublas-cu11 nvidia-cudnn-cu11
export LD_LIBRARY_PATH=`python3 -c 'import os; import nvidia.cublas.lib; import nvidia.cudnn.lib; print(os.path.dirname(nvidia.cublas.lib.__file__) + ":" + os.path.dirname(nvidia.cudnn.lib.__file__))'
```
and now I can run my inference:
```
python3 whisper.py
```

**Comment by remic33** [comment]
Still run into this issue on docker ! 
Any clean solution? 
Was using torch 2.5 torchaudio 2.5 ctranslate2 4.4.0

**Comment by JHC000abc** [comment]
各位大佬，有没有解决方案阿，上边的方案都尝试了

![Image](https://github.com/user-attachments/assets/c2cee936-1d8a-4df1-ac6c-7a898dfec8bb)

![Image](https://github.com/user-attachments/assets/121aaab6-eefb-4ea6-899c-cb4f310ace56)

![Image](https://github.com/user-attachments/assets/0ff376e7-bda6-4315-8733-3f57823761cc)

**Comment by sheldonrong** [comment]
Solution: if you are on `CUDA=12.x` and have `cuDNN=9`, then install `ctranslate==4.5.0`

**Comment by gszep** [comment]
@SeaDude you solution is the only one that worked! thank you

**Comment by bomxacalaka** [comment]
This worked for me: https://github.com/ufal/whisper_streaming/issues/119#issuecomment-2353536504

**Comment by quamranhasan** [comment]
This error occurs because cuDNN is either not installed or not properly linked in your system. Specifically, your program is looking for libcudnn_ops_infer.so.8
Just solved this using these steps:
1. Download cuDNN from [NVIDIA's cuDNN Archive](https://developer.nvidia.com/rdp/cudnn-archive). Make sure to match the cuda version (use nvcc --version)
2. Install the file. In my case, it was: sudo dpkg -i cudnn-local-repo-ubuntu2204-8.9.7.29_1.0-1_amd64.deb
3. sudo apt update
4. sudo apt install libcudnn8 libcudnn8-dev
5. confirm using: cat /usr/include/cudnn_version.h | grep CUDNN_MAJOR -A 2
--> (This should show CUDNN_MAJOR 8, CUDNN_MINOR 9, etc.)

Then you should be good

**Comment by Vlod-github** [comment]
I have `CUDA=12.x` and `cuDNN=9`. Since I wanted to update to the latest possible version of the libraries that support CUDA 12, installing `ctranslate==4.5.0` helped me. Thank you https://github.com/SYSTRAN/faster-whisper/issues/516#issuecomment-2628799793 and setting the LD_LIBRARY_PATH also helped
